# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: branch deploy for Build and deploy ASP.Net Core app to Azure Web App - jamba-asp-dotnet-app

on:
  # The workflow to execute on is comments that are newly created
  issue_comment:
    types: [created]

# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read


jobs:
  build:
    runs-on: windows-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      # Execute IssueOps branch deployment logic, hooray!
      # This will be used to "gate" all future steps below and conditionally trigger steps/deployments

      - name: Branch-deploy action
        uses: github/branch-deploy@v4.1.0
        id: branch-deploy
        with:
          trigger: ".deploy"
        # environment: prod
          environment_targets: "Production,Development"  # the environments that you can deploy to with explicit commands

     # Run your deployment logic for your project here - examples seen below
     
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

# deploy to development 
  deploy_to_dev:
    runs-on: windows-latest
    needs: build
    if: ${{ steps.branch-deploy.outputs.environment == "Development" }}
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'jamba-stagingwebapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FFA2E1C6D75547E6AB167D39C592DEC5 }}
          package: .
	  
	  
# deploy to production 
  deploy_to_prod:
    runs-on: windows-latest
    needs: build
    if: ${{ steps.branch-deploy.outputs.environment == "Production" }}
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'jamba-asp-dotnet-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CC894F96AA154227A2D23756ED193B66 }}
          package: .

